### ISSUE TITLE
예외 경로 관련 기능 고도화 요청

### ISSUE THREAD

**Issue by wonhow** [nanny-i/agent#17]
사용하려는 기능 : 관리자가 지정한 '예외 폴더에서 특정 확장자 파일'은 삭제하지 않는 기능
 
현재 아래 <삭제 정책 항목 예>와 같이 지정했을 때, /home/user/다운로드 하위 모든 문서 삭제됨
/home/user/다운로드 하위의 docx 문서는 삭제되고, hwp 문서는 삭제되지 않도록 고도화 요청
 
<삭제 정책 항목 예>
- 문서 선택 : 개별 문서 확장자
- 문서 확장자 : docx;hwp;
- 검사 대상 : 모든 경로(중요 경로 제외)
- 예외 경로 : /home/user/다운로드/*.hwp
- 검사 경로 : /home/*

**Comment by jhrang** [comment]
1. 원인

 - path string match 부분에 비교 경로에 '/'가 추가되어 동일한 경로로 인식하지 못하는 문제

   [/home/castle/share/doc2 : /home/castle/share/doc2/] [pdf : pdf]

2. 해결방안

- 경로 비교시 '/'가 마지막에 추가되어 있는 경우 제거하고 비교하도록 기능 수정
