### ISSUE TITLE
부팅 후 삭제 대기 시간 설정 기능 동작 안 함

### ISSUE THREAD

**Issue by wonhow** [nanny-i/agent#19]
삭제 정책 항목에서 [검사 주기]를 '시스템 재시작 및 빠른 시작 후 진행합니다. / 40분 후'로 설정하고 테스트했으나, 부팅 후 약 5분 뒤 삭제됨
10분 후로 변경하고 테스트해도 동일하게 5분 뒤 삭제
 
 
- 아래 로그 관련하여 PC 재부팅 시간 : 2020_10_21 15:01경
- 에이전트 sys 로그

2020_10_21 15:06:40     [Info]  set system boot time disable..
2020_10_21 15:06:54     [Info]  [mgr agt po fa clear] valid schedule time : boot wait min : [bt:316][40]
2020_10_21 15:06:54     [Info]  start(check) fa clear schedule : [uid:6][mfoi_optype:1]
2020_10_21 15:06:54     [Info]  [mgr agt po fa clear] fa clear scan info : path : [/home/*]
2020_10_21 15:06:54     [Info]  [mgr agt po fa clear] fa clear scan info : ptn : [pptx;]
2020_10_21 15:06:54     [Info]  [mgr agt po fa clear] fa clear scan info : ex_path : []
2020_10_21 15:06:54     [Info]  [mgr agt po fa clear] fa clear scan info : in_path : [/home/*]
2020_10_21 15:06:54     [Info]  [mgr agt po fa clear] fa clear scan info : reg_path : []
2020_10_21 15:06:54     [Info]  [mgr agt po fa clear] success to add file extension : [901][pptx]
2020_10_21 15:06:54     [Info]  [mgr agt po fa clear] success to add file path : [901][/home/*]
2020_10_21 15:06:54     [Info]  [mgr agt po fa clear] success to add file date time : [901][0][0]
2020_10_21 15:06:54     [Info]  [mgr agt po fa clear] success to add file find option : [901][1]
2020_10_21 15:06:54     [Info]  [mgr agt po fa clear] success to start search dir thread : [901]

**Comment by jhrang** [comment]
1. 원인

 -  부팅 후 무조건 삭제하도록 기능 구현되어 해당 기능이 지원되지 않았음

2. 해결

 - 부팅 후 대기 시간 이후 동작하도록 기능 구현
