### ISSUE TITLE
에이전트 상태 변경 > 삭제 상태 -> 에이전트 삭제 안됨

### ISSUE THREAD

**Issue by jikim2000** [nanny-i/agent#21]
에이전트 상태 변경 -> 삭제 상태로 변경 시 에이전트 삭제 안됨

2020_10_07 14:07:39     [Info]  agt_mgr disconnected [0][][1]
2020_10_07 14:08:40     [Info]  select lgn svr : [192.168.0.105][60010]
2020_10_07 14:08:40     [Info]  start lgn client
2020_10_07 14:08:40     [Info]  [logic lgn svr] login current net hardware info : [192.168.0.88][00:0C:29:22:1C:28:]
2020_10_07 14:08:40     [Info]  [logic lgn svr] login fail : auto remove module
2020_10_07 14:09:41     [Info]  select lgn svr : [192.168.0.105][60010]
2020_10_07 14:09:41     [Info]  start lgn client
2020_10_07 14:09:41     [Info]  [logic lgn svr] login current net hardware info : [192.168.0.88][00:0C:29:22:1C:28:]
2020_10_07 14:09:41     [Info]  [logic lgn svr] login fail : auto remove module
2020_10_07 14:10:42     [Info]  select lgn svr : [192.168.0.105][60010]
2020_10_07 14:10:42     [Info]  start lgn client
2020_10_07 14:10:42     [Info]  [logic lgn svr] login current net hardware info : [192.168.0.88][00:0C:29:22:1C:28:]
2020_10_07 14:10:42     [Info]  [logic lgn svr] login fail : auto remove module
2020_10_07 14:11:21     [Info]  set system boot time disable..
2020_10_07 14:11:43     [Info]  select lgn svr : [192.168.0.105][60010]
2020_10_07 14:11:43     [Info]  start lgn client
2020_10_07 14:11:43     [Info]  [logic lgn svr] login current net hardware info : [192.168.0.88][00:0C:29:22:1C:28:]
2020_10_07 14:11:43     [Info]  [logic lgn svr] login fail : auto remove module
2020_10_07 14:12:44     [Info]  select lgn svr : [192.168.0.105][60010]

**Comment by jhrang** [comment]
1. 에이전트 삭제 정책 추가하여 해당 기능 지원
