### ISSUE TITLE
실시간 감시 정책 설정 시 삭제 안됨

### ISSUE THREAD

**Issue by sklee-lsk** [nanny-i/agent#22]
운영정책 수립 후 삭제 안됨
 - 삭제 주기 : 재부팅/특정 시간(조건 검사 없음) 2가지로 테스트 함
 
- sys 로그 중 Error 일부 캡쳐
2020_10_20 11:24:17     [Error] fail to set po_fa_op_unit by inotify : [-10003]
...
2020_10_20 13:22:30     [Error] fail to set po_fa_op_unit by inotify : [-10012]
...
2020_10_20 13:25:29     [Error] not find po_ctl_panel_pkg information [0]:po_id[0]:[71]
...
2020_10_20 13:44:47     [Error] [ExecuteQuery_Exe] fail to exec INSERT INTO po_in_rs_no(id, used_flag, reg_date, seq_no, name, descr, admin_id, sub_admin_lock, target_lock, notify_info_id, ext_option, used_mode, msg_type) VALUES (1, 1, 1585048737, 0, 'default policy', '', 1, 0, 0, 0, 0, 0, 0) (-1) : sql error, state = HY000, error = 19, [SQLite]UNIQUE constraint failed: po_in_rs_no.id (19)
2020_10_20 13:44:47     [Error] [mgr agt po in rs no] apply policy information : [0]
2020_10_20 13:44:47     [Info]  [mgr agt po in rs no] recv changed policy info : [00000012]
2020_10_20 13:44:47     [Error] [mgr agt po in rs no] set po in rs no fail : not find cur policy

**Comment by jhrang** [comment]
실시간 감시 테스트 방식 오류로 테스트 확인 결과 정상 삭제 확인
완료 처리
