### ISSUE TITLE
삭제 스크립트 syntax error 수정 요청

### ISSUE THREAD

**Issue by sklee-lsk** [nanny-i/agent#23]
패키지 내 삭제 스크립트 22행 syntax error 수정 요청
 
./nanny_uninstall.sh: 22: ./nanny_uninstall.sh: Syntax error: "(" unexpected

**Comment by jhrang** [comment]
1. 원인

에이전트 정리 정책에 의하여 /auto_remove 인자를 받는 부분이 추가되었는데

해당 인자를 받는 부분이 args=("$1") 부분인데 이 부분의 ()가 scripts 에서 적용되지 않는

시스템이 존재

2. 수정

args=("$1") 부분을 args="$1" 형태로 변경
