### ISSUE TITLE
모듈 버전 수정 요청

### ISSUE THREAD

**Issue by ehyam** [nanny-i/agent#25]
리눅스 업데이트 모듈 버전 -> 2.0.0.8  
윈도우 업데이트 모듈 버전 -> 2.0.3.20 
 
콘솔 > 조직관리 > 모듈 버전 2.0.3.20으로 표시됨
이에 리눅스 업데이트 모듈 버전과 동일하게 표시 요청

**Comment by jhrang** [comment]
- 리눅스와 윈도우 기능의 차이로 인해 윈도우 기능이 업데이트 되었다고 리눅스 기능이 업데이트 되지 않는 경우가 발생
- 해당 이유로 리눅스와 윈도우의 버전은 별도로 관리
