### ISSUE TITLE
[에이전트] 삭제 정책 > 문서 포맷 사용 및 검사 경로 2개 이상 일 때 문서 포맷 삭제 검토 요청

### ISSUE THREAD

**Issue by jikim2000** [nanny-i/agent#32]
1. 에이전트버전 : [2.0.0.11]
2. 현상
 - 확장자 xlsx,docx 등등 문서 포맷 사용함
 - 검사 경로 /home/*,/root/test/*
 -  결과: /home 및 /root/test 하위에 있는 문서가 모두 삭제되어야 정상이지만, 완벽하게 삭제되지 않음
        이후, 동일한 파일 업로드하여 재 시도 했을 때 지워졌던 파일이 안지워지거나 등 불규칙적으로 삭제 됨
 ** 검사 경로를 1개만 넣었을 경우에는 정상 삭제 됨.

**Comment by jhrang** [comment]
1. 원인 

 - 멀티쓰레드 환경에서 다중 검사시 문서 포맷 검사 동기화 처리가 되지 않아서 발생한 문제

2. 해결 

 - 멀티쓰레드 환경에서 다중 검사시 문서 포맷 검사 동기화 처리
