### ISSUE TITLE
[에이전트] 확장자 대소문자 구분 요청

### ISSUE THREAD

**Issue by jikim2000** [nanny-i/agent#33]
1. 에이전트버전 : [2.0.0.11]
2. 현상
 - 파일 확장자 대소문자 구분 없이 삭제 됨 (첨부파일 확인)
 ex) 확장자  zip   -> zip, Zip, ZIP, zIP 모두 삭제

**Comment by jhrang** [comment]
1. 원인 

 - Windows에서는 대소문자 구분이 없기 때문에 해당 모든 경로 및 파일에 대하여 소문자로 변환하여 비교

2. 해결

 - 대소문자를 구분하여 경로 및 파일 비교하도록 수정
