### ISSUE TITLE
[에이전트]삭제 정책>예외 경로 대소문자 구분 필요

### ISSUE THREAD

**Issue by jikim2000** [nanny-i/agent#34]
1. 에이전트버전 : [2.0.0.11]
2. 현상
 - 예외경로 /home/Log/* 
 - 검사경로 /home  설정 후, 삭제 정책 실행 시 /home/log,/home/Log,/home/LOG 제외한 나머지만 삭제
  -> /home/Log만 예외하고 나머지는 삭제되어야 정상
 ** 검사 경로는 대소문자 구분하여 삭제 됨
   TEST 경로 : /home/Log, /home/LOG, /home/log

**Comment by jhrang** [comment]
1. 원인 

 - Windows에서는 대소문자 구분이 없기 때문에 해당 모든 경로 및 파일에 대하여 소문자로 변환하여 비교

2. 해결

 - 대소문자를 구분하여 경로 및 파일 비교하도록 수정
