### ISSUE TITLE
로그 조회 기간 설정 시 사용하는 달력 컨트롤 관련 수정 요청

### ISSUE THREAD

**Issue by toins119** [nanny-i/agent#4]
로그 조회 기간 설정 시 사용하는 달력 컨트롤에서 아래 2개 항목 수정 요청드립니다.
1. 달력 양 옆 잘림
2. 이전, 다음 달로 이동하는 버튼 없음

**Comment by wonhow** [comment]
로그 조회 기간 설정 시 사용하는 달력 컨트롤에서 아래 2개 항목 수정 완료

달력 양 옆 잘림 해결
이전, 다음 달로 이동하는 버튼 없음 해결

**Comment by jhrang** [comment]
로그 조회 기간 설정 시 사용하는 달력 컨트롤에서 아래 2개 항목 수정 완료

달력 양 옆 잘림 해결
이전, 다음 달로 이동하는 버튼 없음 해결
