### ISSUE TITLE
[에이전트] zip 파일과 office 문서 파일 구분 실패

### ISSUE THREAD

**Issue by augbie** [nanny-i/agent#45]
삭제 정책 -> 문서 파일 헤더 검사
 
 - office 파일은 삭제 필요
 - zip 파일은 삭제 예외
 - zip 파일은 office 파일과 구분 요청

**Comment by jhrang** [comment]
1. 원인 : office 문서 파일와 zip 파일은 동일한 문서 형식이어서 구분 불가
2. 해결 : 최초 문서 파일명을 구분하여 파일 구분
