### ISSUE TITLE
[에이전트] 티맥스OS에 에이전트 설치 시 odbc 관련 오류

### ISSUE THREAD

**Issue by ytryu12** [nanny-i/agent#46]
링크를 통해 다운로드 받은 신규 티맥스OS 설치 후
에이전트 설치 중 실패(구동도 안 됨)
 
1. 에이전트 설치 로그
2020년 11월 03일 (화) 오전 09시 28분 56초       /usr/bin/ldd /usr/local/ashin/nanny/sbin/nannysvc
        linux-vdso.so.1 (0x00007fffd73d0000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f8e51e79000)
        libodbc.so.2 => not found
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8e51e74000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8e51e53000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f8e51e49000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8e51c88000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8e532bf000)
2020년 11월 03일 (화) 오전 09시 28분 56초       /usr/bin/ldd /usr/local/ashin/.tools/dbuse
        linux-vdso.so.1 (0x00007ffe417d9000)
        libodbc.so.2 => not found
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc218410000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc21824f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc21872a000)

**Comment by jhrang** [comment]
1. 원인 : 신규 TMaxOS가 dpkg에 설치 정보가 변경되어 설치 여부를 판단하지 못하는 문제
2. 해결 : odbc 설치 여부는 /usr/bin/odbcinst 파일 존재 여부로 /usr/bin/sqlite3 파일 존재 여부로 판단하여 설치 진행
