### ISSUE TITLE
[콘솔] 에이전트 정리 정책 의한 에이전트 상태 변경 시 삭제 에이전트 탭 정보 미 표시

### ISSUE THREAD

**Issue by wonho6954** [nanny-i/agent#63]
에이전트 정리 정책 실행 시,
로그는 정상적으로 삭제 상태로 변경되었다고 남지만(첨부 파일 확인), 삭제 에이전트 탭에는 에이전트 정보가 보이지 않음
(휴면 에이전트 탭으로 이동했을 때에는 보임)
 
추가로, 정리 정책에 의해 휴먼 에이전트 탭으로 이동 된 후 서버 업데이트 하면 휴먼 에이전트 탭에 있던 에이전트 정보가 사라짐

**Comment by jhrang** [comment]
에이전트 관리 -> 정리 정책 -> 바로 삭제
조직 관리 -> 에이전트 상태 변경 -> 에이전트가 연결 되어 있으면 곧 바로 삭제 (조직관리 삭제 에이전트에 남지 않음)
에이전트가 연결 되어 있지 않으면 에이전트가 접속 할 때까지 삭제 에이전트 목록에 남아 있는 상태이고 후에 에이전트가 접속 하면 삭제되는 형태로 구현됨
