### ISSUE TITLE
[콘솔] 에이전트 관리 > 운영 정책 > 부팅 기준 기본 값 설정 관련

### ISSUE THREAD

**Issue by wonho6954** [nanny-i/agent#64]
에이전트 관리 > 운영 정책 > 기본 탭 > 부팅 기준 값을
자동 감지로 비활성화 처리 요청

**Comment by jhrang** [comment]
에이전트 관리 > 운영 정책 > 기본 탭 > 부팅 기준 값을
자동 감지하여 활성화되도록 기능 수정
