### ISSUE TITLE
[에이전트] 멀티 부팅 사용 시 내용 확인 건

### ISSUE THREAD

**Issue by wonho6954** [nanny-i/agent#65]
현재 조직 관리에 정보는 한대만 표시 되고, 다른 OS로 부팅 시에 정보만 변경되어 표시되는 문제 검토 요청

**Comment by jhrang** [comment]
멀티 부팅을 사용하는 물리 PC의 실제 부팅은 1가지 OS만 가능하므로, 콘솔에는 3개 OS 중 부팅된 OS 정보만 갱신되어 출력하는 방식으로 구현되었기 때문에 해당 이슈 종료
