### ISSUE TITLE
[서버/콘솔] 업데이트 정책이 수동으로 설정되어 있으나 자동으로 업데이트됨

### ISSUE THREAD

**Issue by wonho6954** [nanny-i/agent#66]
에이전트 관리 - [업데이트 정책] : '관리자에 의해 업데이트를 수동으로 진행합니다.'로 설정되어 있는 상태에서
서버, 콘솔만 업데이트 진행했으나 업데이트 정책이 자동으로 업데이트됨
업데이트 적용을 누르기 전까지 업데이트가 진행되지 않도록 수정 요청

**Comment by jhrang** [comment]
업데이트 적용 버튼을 클릭할 때 업데이트 로직이 진행되도록 기능 수정
